package mj23gym.util;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public final class ReportPdfExporter {
    private static final DateTimeFormatter DATE_TIME_FORMAT =
        DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a");

    private ReportPdfExporter() {
    }

    public static Path exportReport(
        String reportName,
        String reportType,
        Date periodStart,
        Date periodEnd,
        String generatedBy,
        Timestamp generatedAt,
        String notes,
        Path outputFile
    ) throws IOException {
        Files.createDirectories(outputFile.getParent());
        List<String> lines = buildLines(reportName, reportType, periodStart, periodEnd, generatedBy, generatedAt, notes);
        Files.write(outputFile, buildPdf(lines));
        return outputFile;
    }

    private static List<String> buildLines(
        String reportName,
        String reportType,
        Date periodStart,
        Date periodEnd,
        String generatedBy,
        Timestamp generatedAt,
        String notes
    ) {
        List<String> lines = new ArrayList<>();
        lines.add("MJ23 Playgrind Gym");
        lines.add(reportName != null ? reportName : "Generated Report");
        lines.add("");
        lines.add("Type: " + value(reportType));
        lines.add("Period: " + value(periodStart) + " to " + value(periodEnd));
        lines.add("Generated by: " + value(generatedBy));
        lines.add("Generated at: " + (generatedAt != null
            ? generatedAt.toLocalDateTime().format(DATE_TIME_FORMAT)
            : "Current session"));
        lines.add("");
        lines.add("Report Details");
        lines.add("");
        String body = notes == null || notes.isBlank() ? "No report details available." : notes;
        for (String rawLine : body.replace("\r", "").split("\n")) {
            lines.addAll(wrap(rawLine, 92));
        }
        return lines;
    }

    private static byte[] buildPdf(List<String> lines) throws IOException {
        int linesPerPage = 45;
        int pageCount = Math.max(1, (int) Math.ceil(lines.size() / (double) linesPerPage));
        List<String> objects = new ArrayList<>();
        objects.add("<< /Type /Catalog /Pages 2 0 R >>");

        StringBuilder kids = new StringBuilder();
        int firstPageObject = 4;
        for (int page = 0; page < pageCount; page++) {
            if (page > 0) {
                kids.append(' ');
            }
            kids.append(firstPageObject + page * 2).append(" 0 R");
        }
        objects.add("<< /Type /Pages /Kids [" + kids + "] /Count " + pageCount + " >>");
        objects.add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

        for (int page = 0; page < pageCount; page++) {
            int pageObject = firstPageObject + page * 2;
            int contentObject = pageObject + 1;
            objects.add("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents " + contentObject + " 0 R >>");
            String content = pageContent(lines, page * linesPerPage, Math.min(lines.size(), (page + 1) * linesPerPage));
            objects.add("<< /Length " + content.getBytes(StandardCharsets.ISO_8859_1).length + " >>\nstream\n" + content + "endstream");
        }

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        write(out, "%PDF-1.4\n");
        List<Integer> offsets = new ArrayList<>();
        offsets.add(0);
        for (int i = 0; i < objects.size(); i++) {
            offsets.add(out.size());
            write(out, (i + 1) + " 0 obj\n");
            write(out, objects.get(i));
            write(out, "\nendobj\n");
        }

        int xrefOffset = out.size();
        write(out, "xref\n0 " + (objects.size() + 1) + "\n");
        write(out, "0000000000 65535 f \n");
        for (int i = 1; i < offsets.size(); i++) {
            write(out, String.format("%010d 00000 n \n", offsets.get(i)));
        }
        write(out, "trailer\n<< /Size " + (objects.size() + 1) + " /Root 1 0 R >>\n");
        write(out, "startxref\n" + xrefOffset + "\n%%EOF\n");
        return out.toByteArray();
    }

    private static String pageContent(List<String> lines, int from, int to) {
        StringBuilder content = new StringBuilder();
        content.append("BT\n/F1 11 Tf\n14 TL\n50 742 Td\n");
        for (int i = from; i < to; i++) {
            if (i == from) {
                content.append("(").append(escape(lines.get(i))).append(") Tj\n");
            } else {
                content.append("T*\n(").append(escape(lines.get(i))).append(") Tj\n");
            }
        }
        content.append("ET\n");
        return content.toString();
    }

    private static List<String> wrap(String line, int maxLength) {
        List<String> wrapped = new ArrayList<>();
        if (line == null || line.isBlank()) {
            wrapped.add("");
            return wrapped;
        }
        String remaining = line;
        while (remaining.length() > maxLength) {
            int breakAt = remaining.lastIndexOf(' ', maxLength);
            if (breakAt <= 0) {
                breakAt = maxLength;
            }
            wrapped.add(remaining.substring(0, breakAt));
            remaining = remaining.substring(breakAt).trim();
        }
        wrapped.add(remaining);
        return wrapped;
    }

    private static String escape(String value) {
        return value
            .replace("\\", "\\\\")
            .replace("(", "\\(")
            .replace(")", "\\)")
            .replace("₱", "PHP");
    }

    private static String value(Object value) {
        return value == null ? "-" : value.toString();
    }

    private static void write(ByteArrayOutputStream out, String value) throws IOException {
        out.write(value.getBytes(StandardCharsets.ISO_8859_1));
    }
}
